name: Brickhu.cn
description: A Design Thinker who focuses on the architecture , communication and quality of information.
auto: true
permalink: /:categories/:year/:month/:title/
markdown: rdiscount
exclude:
  - Rakefile
  - Gemfile
  - .gitignore